### ISSUE TITLE
Model for architecting environments at enterprise scale

### ISSUE THREAD

**Issue by andrewdwelch** [PowerPlatformAF/PowerPlatformAF#22]
Would be good if we had a model (or more likely several) that provides guidance as to how environments should be architected, arranged, integrated with one another in large organizations. Perhaps pose a few different scenarios and discuss the advantages and disadvantages of each?

Need to consider how Dynamics fits into this picture.

Define tiers of applications:

- Critical
- Important
- Productivity

**Comment by manuelap-msft** [comment]
https://powerapps.microsoft.com/en-us/blog/establishing-an-environment-strategy-for-microsoft-power-platform/

**Comment by andrewdwelch** [comment]
Need also to clarify here what the purpose of the Default environment is ("Sandbox for All"), e.g. rename it "Personal Productivity".

**Comment by andrewdwelch** [comment]
@LeeMBaker and I have created the **Environmental Architecture Model** and inserted it as a new section in Power Platform Adoption Framework. See link below.

https://github.com/PowerPlatformAF/PowerPlatformAF/wiki/3---Enterprise-Management#environmental-architecture-model

Closing this item.
