### ISSUE TITLE
Change Program Management Pillar to Platform Management

### ISSUE THREAD

**Issue by edcartner** [PowerPlatformAF/PowerPlatformAF#30]
Dimensions become (not necessarily in this order): 
Project Tooling
Backlog Management
Road Mapping
COE Starter Kit
COE Establishment

**Comment by andrewdwelch** [comment]
Yes yes yes. "Platform Management" is so much better and to the point than "Program Management".

This is a pretty small change, so I am just going to move it to work on the current edition unless I hear objection from anyone.

**Comment by andrewdwelch** [comment]
This has now been updated at https://github.com/PowerPlatformAF/PowerPlatformAF/wiki/4---Enterprise-Management#pillars-of-enterprise-management.
